language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-22.0.1
  - android-22
env:
  global:
  - secure: ewXrx48ipaO27+r8Q+KY91fIC3fnYkruQnaYYdTKg/b7AjTMzLpVLmngXAK23H4bEwHMWSmtF8lPIwMVlej8MhAyj/7mOUQzPJsKkog4SjcOXmPXCTXy3zYL9MFHsnm7AD5cxEP6VYYE49stWZp45uIAbcUGMJG51nwN//TH3iQ+HDcIb892tUSs0G98xaWtzHaRYeCU6q/mUw9HfaLwG1VqJZ6tN93qi302zYLAgmXyPfb6dUivyEt9lub+RD+hiB7+aMIwsT/n7ZyUCgqc4hQsHx37LHxr/jhOYEdBNYOw6iQvjEnZ3IvPKzPCeyfCgLurWI0Z9390e8N6zjNRHzdflB6sVGtCKpf649ODtiu3lB7tlGRU33rYiPcpsyETYBUZHhmXHi72vWTgNSGIljCJS5EAi8f+mZHQeDnrxjWUM8HpnmcNFdYvMpzVb2AF9QXpJ8ZPkqi7IMVwGrQAdhcI2uyveVPXGXNyoGEGdFYSolnhKRIqPc3X3gO8fUxKBst1cVeQjvPN8RLo6lH24GOnvQKOWtc826g7lt7dd4sLyNyE6Jtj6XHSYCxW3oLi/1ZL/Jp5U9VZQNMx0k43/JXHUJRgOvXFnBoNdbF3kizJziC2syaMumcZSGT+u8mbGip40TTxwplnikwEE04sEIpkwPABuHZxTqZR01bXj/Q=
  - secure: UzU6fTpckQoou0vwvYOezacKpAFnq54asucdqktK06wC4VBoWiZPvwSRWsfJs/7dOr3Mq35aWKT3C7aBLlhRNm0YrmTSjCAc1vslpCGlpWDc/TJGlf5wbpYsjgzRz06PH/mR1LybeA7GHK1ja8GDtzLooigOqgQrAVQuOwosCHbjFGq3fAmzjEvpHJ/58BYHWi3FOu6oenz5VL43UVk1rbi4CZMz7Gqx9LDvJvmsepW+aGXOdVRvgFvWxhHSA7w8JqT2v5q90E2bJQgXR+wLAoSr+9D3/385QQpYOzqn74OS504F3OiKI2FwgQCHc2gSNz2nQtApZ5R4tIbZOrwnH1hLow+szVqH9B0SwC4laJuHtKB09JY0pMv6Gb8so5RLf2KVE7l8TG+KTaUdwkl7mfS+QD6dMyIK84n6V0NKzMN9v4XaMzVgj0T673xJPA3vRXqG4wWov9vuNVL0E8nvDvHOqYOgjsDrsEw2Zg23DIxvk+aKmHVBPb9It9dunI5Okl7vBlvU2ds8tTZAtIHPyo58cOfZPKEH0f2uEHHRf0RNdPkWBLg1j6mI47CYgb0Gon1hDwjkvAfD7JTguIvCxukY0cwv0Ed9g5OhkPQj/EN4qWoxa0dz/xwFKEj2iqVHlnOXVlWBY8yj8W5C7SBKDh54r8EMuTocjD7Tp8fwYc8=
cache:
  directories:
  - node_modules
  - src/lib
before_install:
- echo "Before install stage"
install:
- echo "Install stage"
- nvm install 0.12.6
- npm install
- export PATH=$(npm bin):$PATH
- export PATH=$ANDROID_HOME/build-tools/22.0.1:$PATH
- bower install
before_script:
- echo "Before script stage"
script:
- echo "Script stage"
- cordova plugin add https://github.com/apache/cordova-plugin-console
- cordova plugin add https://github.com/apache/cordova-plugin-splashscreen
- cordova plugin add https://git-wip-us.apache.org/repos/asf/cordova-plugin-whitelist.git
- cordova plugin add org.apache.cordova.device
- cordova plugin add https://github.com/driftyco/ionic-plugins-keyboard.git
- cordova plugin add org.apache.cordova.inappbrowser
- cordova plugin add org.apache.cordova.file
- cordova plugin add org.apache.cordova.file-transfer
- ionic platform add android
after_success:
- bash ./travis-release.sh -k my-release-key.keystore
after_failure:
- echo "After failure stage"
after_script:
- echo "After script stage"
deploy:
  provider: releases
  api_key:
    secure: iEfAIOomzTtPrzfQq1+Hw4GAMN8G/txc0ES9MjdpUcHWvSRAJvjfQStcygZ32PsEMX9KarZo6IizfCw4jbmi/vpCA5TGsDIbt0Z7/tX/yf65pItetu5G1T1VSbEAD2Ov6WGZmqW0z2ZTjDAljSYCSryasew0I3D64a54YYa+UPOzMkfmyT/ZhvdgVBBG6x8KY/+ksrmRRLJ78sEf84khsfT8mHlqVb54JjJPeSt0bmiy7iHEkgLkB8lnmp/VhaEAkSTr+5ziR/HmIeFFcc3Yv/oYBiwy2bXo/pILwzGvMfL9pA0ybJbpcuOT9wj/oyG82iO9S8WkmehA3evcoTJ8pwT6D1zxbVXSPJZAdTjcwxdAsLJEPqAL6NBXNXO92b9k7yIdgUslGbY5PYQrV13lcylcIbZyUqUgLXwQyoRat9kE0Ef/U0Ce7qTC0DaT2j2/0gZYXyglzEsnVFe7Gvy7mk2IialaZgR7Dpixsy9eByzpUOJ5nJPuERnDLJLXCp1B1DDZkfh+WAjJ13Ho4+Y/uNvwLtrjrC51U/qnZh5ptVkrFnBOg0YzCLh9gkCgrFW1YKEU8Fgw4Q67bcProtBt8aVo/WMwfpua6ThxKe46zCDyKMll646G7X+V/pC6VqiyMUnhhY4Ec/oFEZ5XkMKJOY1abmwTX2g6Nm0KIWgqL5U=
  file: easydownload.apk
  on:
    tags: true
    all_branches: true
